project:
  type: default
  output-dir: _output

format:
  revealjs:
    theme: [default, custom.scss]
    slide-number: true
    center: false
    auto-stretch: false
    width: 1600
    height: 900
    margin: 0.05
    transition: fade
    transition-speed: fast
    highlight-style: github
    code-overflow: wrap
    mermaid:
      theme: neutral
    mermaid-format: png
    footer: "CAR Mobility Systems Lab | OSC Overview"
